version: 0.1

phases:
    install:
         commands:
            - apt-get -y update
            - apt-get -y install zip
            - apt-get -y install python3.4
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install awscli
    pre_build:
         commands:
            - aws apigateway get-rest-apis --region us-east-1 --no-paginate
    build:
         commands:
            - dotnet restore
            - dotnet publish core.api -c Release -o out
            - cd out
            - zip -r core.api/publish.zip out/*
artifacts:
    files:
         - core.api/serverless.template
         - core.api/publish.zip