phases:
    install:
         commands:
            - apt-get -y update
            - apt-get -y install zip
    build:
         commands:
            - dotnet restore 
            - cd core.api 
            - dotnet publish -c Release -o out 
            - cd out 
            - zip -r ../publish.zip *
artifacts:
    files:
         - core.api/serverless.template
         - core.api/publish.zip