version: 0.1

phases:
    install:
         commands:
            - apt-get -y update
            - apt-get -y install zip
            - apt-get -y install python3.4
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python3 get-pip.py --user
            - pip install awscli --upgrade --user
    pre_build:
         commands:
            - aws-cli list-functions --no-paginate
    build:
         commands:
            - dotnet restore 
            - cd core.api 
            - dotnet publish -c Release -o out 
            - cd out 
            - zip -r ../publish.zip *
artifacts:
    files:
         - core.api/serverless.template
         - core.api/publish.zip